#define UNEXPECTED -1
#define KEYWORD 1
#define SOURCE 2
#define PARAMETER 3
#define VARIABLE 4
#define STRING 5
#define NUMBER 6
#define COMMENT 7
#define OPERATOR 8
#define FUNCTION 9
#define EOQ 10
#define FIELD 11
#define SEPERATOR 12
#define SELECT 13
#define FROM 14
#define WHERE 15
#define AND 16
#define OR 17
#define PARENTHESIS_OPEN 18
#define PARENTHESIS_CLOSE 19
#define BRACKET_OPEN 20
#define BRACKET_CLOSE 21
#define CURLY_BRACKET_OPEN 22
#define CURLY_BRACKET_CLOSE 23
#define LIMIT 24
#define START 25
